name: NPM Worker
description: An action to init and manage node modules on your repo
author: Mudlabs
branding:
  icon: package
  color: yellow
inputs:
  token:
    description: GITHUB_TOKEN or a PAT for the repository
    required: false
    default: ${{ github.token }}
  config:
    description: A path to the configuration file for the worker
    required: false
outputs:
  activity:
    description: Describes the activity perfomed by the action.
runs:
  using: node12
  main: action.js
