name: NPM Worker
description: An action to init and manage node modules on your repo
author: Mudlabs
branding:
  icon: package
  color: yellow
outputs:
  activity:
    description: A description of the changes made.
runs:
  using: node12
  main: index.js
