name: Test Worker

on:
  push:
    paths: 
      - test/npm.?worker.config.ya?ml

env:
  GITHUB_REF: ${{ github.ref }}
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        uses: nelonoel/branch-name@v1
      - run: echo ${BRANCH_NAME}
#       - name: Worker
#         run: echo mudlabs/npm-worker@ ${{ env.GITHUB_REF }}
#         with:
#           config: ./test/
