name: Test Worker

on:
  push:
    paths: 
      - test/npm.?worker.config.ya?ml

env:
  GITHUB_REF: ${{ github.ref }}
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Worker
        uses: mudlabs/npm-worker@${{ env.GITHUB_REF }}
        with:
          config: ./test/
