name: Test Worker

on:
  push:
    paths: 
      - test/npm.?worker.config.ya?ml
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Worker
        uses: mudlabs/npm-worker@master
        with:
          config: ./test/
      - name: Commit
        uses: EndBug/add-and-commit@v5.1.0
