name: Test Worker

on:
  push:
    paths: 
      - test/npmworker.config.yaml
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Worker
        uses: ./
        with:
          config: ./test/npmworker.config.yaml
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.0.0
