name: Test Worker

on:
  push:
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Worker
        uses: ./
        with:
          config: ./test/npmworker.config.yaml
