name: Test Worker

on:
  push:
    paths: 
      - test/npm.?worker.config.ya?ml
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        uses: nelonoel/branch-name@v1
      - name: Worker
        uses: refs/heads/master
        with:
          config: ./test/
