name: NPM Worker

on:
  push:

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - name: Install
#         id: install
#         run: npm install js-yaml
#       - name: Add & Commit
#         uses: EndBug/add-and-commit@v5.0.0
