name: NPM Worker

on:
  push:
    paths-ignore: 
      - test/**

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
