name: NPM Worker

on:
  push:
    paths-ignore: 
      - test/**

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
