name: NPM Worker

on:
  push:
    paths-ignore: 
      - test/**

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ env.GITHUB_REF }}
    steps:
      - uses: actions/checkout@v2
      - name: ${{ steps.outputs.ref }}
        run: |
          echo github.ref if ${{ github.ref }}
          echo github.event_name is: ${{ github.event_name }}
